import { SaveManager } from '../storage/SaveManager';
export type AudioCue='hit'|'block'|'success'|'wrong'|'jump'|'voiceOn'|'voiceCommit'|'voiceSuccess'|'voiceFail';
const files:Partial<Record<AudioCue,string>>={hit:'/assets/audio/hit.ogg',block:'/assets/audio/block.ogg',voiceOn:'/assets/audio/voice-on.ogg',voiceCommit:'/assets/audio/voice-commit.ogg',voiceSuccess:'/assets/audio/voice-success.ogg',voiceFail:'/assets/audio/voice-fail.ogg'};
export class AudioManager {
  private context?:AudioContext;private readonly active=new Set<HTMLAudioElement>();
  private getContext():AudioContext|undefined{if(typeof window==='undefined')return;const Context=window.AudioContext;if(!Context)return;this.context??=new Context();return this.context;}
  play(type:AudioCue):void{const source=files[type];if(source){const audio=new Audio(source);audio.preload='auto';audio.volume=SaveManager.load().settings.soundVolume;this.active.add(audio);audio.addEventListener('ended',()=>this.active.delete(audio),{once:true});void audio.play().catch(()=>{this.active.delete(audio);this.playSynth(type);});return;}this.playSynth(type);}
  playEffect(effectId:string,profile:string):void{const context=this.getContext();if(!context)return;if(context.state==='suspended')void context.resume();const hash=[...effectId].reduce((sum,value)=>sum+value.charCodeAt(0),0),now=context.currentTime,volume=SaveManager.load().settings.soundVolume;const bases:Record<string,number>={metal:190,mystic:420,nature:310,water:260,electric:520,food:350,paper:390,transit:150};const base=(bases[profile]??300)+(hash%9)*17;[0,.07,.14].forEach((offset,index)=>{const oscillator=context.createOscillator(),gain=context.createGain();oscillator.type=profile==='metal'||profile==='transit'?'square':profile==='electric'?'sawtooth':profile==='mystic'?'sine':'triangle';oscillator.frequency.setValueAtTime(base*(1+index*.24),now+offset);oscillator.frequency.exponentialRampToValueAtTime(base*(1.35+index*.2),now+offset+.12);gain.gain.setValueAtTime(.0001,now+offset);gain.gain.exponentialRampToValueAtTime((.055-index*.009)*volume,now+offset+.012);gain.gain.exponentialRampToValueAtTime(.0001,now+offset+.16);oscillator.connect(gain).connect(context.destination);oscillator.start(now+offset);oscillator.stop(now+offset+.18);});}
  private playSynth(type:AudioCue):void{const context=this.getContext();if(!context)return;if(context.state==='suspended')void context.resume();const oscillator=context.createOscillator(),gain=context.createGain(),now=context.currentTime;const config={success:[660,.16,'sine'],wrong:[85,.2,'sawtooth'],jump:[380,.08,'sine'],hit:[110,.07,'sawtooth'],block:[260,.08,'square'],voiceOn:[440,.09,'sine'],voiceCommit:[620,.08,'sine'],voiceSuccess:[720,.22,'sine'],voiceFail:[120,.13,'triangle']}as const;const[frequency,duration,wave]=config[type];oscillator.type=wave;oscillator.frequency.setValueAtTime(frequency,now);if(type==='success'||type==='voiceSuccess')oscillator.frequency.exponentialRampToValueAtTime(980,now+duration);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.11*SaveManager.load().settings.soundVolume,now+.01);gain.gain.exponentialRampToValueAtTime(.0001,now+duration);oscillator.connect(gain).connect(context.destination);oscillator.start(now);oscillator.stop(now+duration+.02);}
  close():void{this.active.forEach((audio)=>{audio.pause();audio.src='';});this.active.clear();if(this.context&&this.context.state!=='closed')void this.context.close();this.context=undefined;}
}
